/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LocationResponse } from '../../models/location-response';

export interface SearchLocationByNumber$Params {
  'location-number': number;
  'location-type': string;
}

export function searchLocationByNumber(http: HttpClient, rootUrl: string, params: SearchLocationByNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LocationResponse>>> {
  const rb = new RequestBuilder(rootUrl, searchLocationByNumber.PATH, 'get');
  if (params) {
    rb.path('location-number', params['location-number'], {});
    rb.query('location-type', params['location-type'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LocationResponse>>;
    })
  );
}

searchLocationByNumber.PATH = '/locations/search/number/{location-number}';
