services:
  postgres:
    container_name: postgres-hotel-order
    image: postgres:alpine
    environment:
      POSTGRES_USER: hab
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: hotel_order_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - hotel-order

  ho-api-1:
    container_name: ho-api-1
    image: habtamudires/hotel-order-api:latest
    ports:
      - "8088:8088"
    environment:
      JWT_SECRET_KEY: 9xCv/yYKM/xwcy5H5oQbKAy7ZEyJE/XW0AVU/HJ0Vqd3mjZlspG3+HrukQMBfgnF
      ALLOWED_ORIGINS: http://192.168.43.116:8080,http://localhost:8080
      SERVER_URL: http://192.168.43.116:8088/api/v1
      SERVER_NAME: ho-api-one
      FILE_PATH: /app/uploads
    networks:
      - hotel-order
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads

  ho-api-2:
    container_name: ho-api-2
    image: habtamudires/hotel-order-api:latest
    ports:
      - "8089:8088"
    environment:
      JWT_SECRET_KEY: 9xCv/yYKM/xwcy5H5oQbKAy7ZEyJE/XW0AVU/HJ0Vqd3mjZlspG3+HrukQMBfgnF
      ALLOWED_ORIGINS: http://192.168.43.116:8080,http://localhost:8080
      SERVER_URL: http://192.168.43.116:8088/api/v1
      SERVER_NAME: ho-api-two
      FILE_PATH: /app/uploads
    networks:
      - hotel-order
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads

  ho-ui:
    container_name: ho-ui
    image: habtamudires/hotel-order-ui:latest
    environment:
      API_URL: http://192.168.43.116:8080/api/v1
    ports:
      - "8080:80"
    networks:
      - hotel-order

networks:
  hotel-order:
    driver: bridge

volumes:
  postgres:
    driver: local

