services:
  postgres:
    container_name: postgres-hotel-order
    image: postgres:alpine
    environment:
      POSTGRES_USER: hab
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: hotel_order_db
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - hotel-order

  ho-api:
    container_name: ho-api
    image: habtamudires/hotel-order-api:1.0.1
    ports:
      - "8088:8088"
    networks:
      - hotel-order
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads

  ho-ui:
    container_name: ho-ui
    image: habtamudires/hotel-order-ui:1.0.1
    ports:
      - "8080:80"
    networks:
      - hotel-order
    depends_on:
      - ho-api

volumes:
  postgres:
    driver: local

networks:
  hotel-order:
    driver: bridge