/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryResponse {
  description?: string;
  id?: string;
  imageUrl?: string;
  name?: string;
  parentCategory?: CategoryResponse;
  popularityIndex?: number;
  subCategories?: Array<CategoryResponse>;
}
