/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoryResponse } from '../models/category-response';
export interface ItemResponse {
  category?: CategoryResponse;
  description?: string;
  id?: string;
  imageUrl?: string;
  isAvailable?: boolean;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  name?: string;
  popularityIndex?: number;
  price?: number;
  stockQuantity?: number;
}
