/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ItemRequest {
  categoryId: string;
  description: string;
  id?: string;
  imageUrl?: string;
  isAvailable: boolean;
  name: string;
  price: number;
  stockQuantity?: number;
}
