/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderDetailRequest {
  id?: string;
  itemId?: string;
  itemName?: string;
  note?: string;
  orderId?: string;
  price?: number;
  quantity?: number;
  type?: string;
}
