/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderDetailResponse {
  id?: string;
  itemId?: string;
  itemName?: string;
  note?: string;
  orderId?: string;
  price?: number;
  quantity?: number;
  status?: 'PENDING' | 'READY' | 'PROCESSED' | 'CANCELLED';
  type?: string;
}
