/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderedItemsFrequencyResponse {
  frequency?: number;
  imageUrl?: string;
  itemName?: string;
  price?: number;
}
