/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationRequest {
  email?: string;
  firstName: string;
  id?: string;
  lastName: string;
  password: string;
  phoneNumber: string;
  roles: Array<string>;
  username: string;
}
