/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LocationResponse } from '../models/location-response';
export interface ServiceRequestResponse {
  completedAt?: string;
  createdAt?: string;
  id?: string;
  location?: LocationResponse;
  locationId?: string;
  serviceStatus?: 'PENDING' | 'CANCELED' | 'COMPLETED';
  serviceType?: 'CALL' | 'BILL';
}
