/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ServiceRequestResponse } from '../../models/service-request-response';

export interface GetPendingServiceRequests$Params {
}

export function getPendingServiceRequests(http: HttpClient, rootUrl: string, params?: GetPendingServiceRequests$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ServiceRequestResponse>>> {
  const rb = new RequestBuilder(rootUrl, getPendingServiceRequests.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ServiceRequestResponse>>;
    })
  );
}

getPendingServiceRequests.PATH = '/service-requests/pending';
