/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryRequest {
  description?: string;
  id?: string;
  imageUrl?: string;
  name: string;
  parentCategoryId?: string;
  popularityIndex?: number;
}
