/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DayOfTheWeekAnalysisResponse {
  averageOrder?: number;
  averageTransaction?: number;
  dayOfTheWeek?: string;
}
