/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LocationResponse {
  address?: string;
  description?: string;
  id?: string;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  number?: number;
  status?: 'OCCUPIED' | 'ONCHANGE' | 'READY' | 'DND' | 'OOO';
  type?: 'TABLE' | 'ROOM';
}
