/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LocationRequest {
  address: string;
  description: string;
  id?: string;
  number: number;
  status: string;
  type: string;
}
