/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  accountLocked?: boolean;
  email?: string;
  firstName?: string;
  id?: string;
  imageUrl?: string;
  lastName?: string;
  password?: string;
  phoneNumber?: string;
  roles?: Array<string>;
  username?: string;
}
