/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderResponse } from '../../models/order-response';

export interface GetPendingOrders$Params {
}

export function getPendingOrders(http: HttpClient, rootUrl: string, params?: GetPendingOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderResponse>>> {
  const rb = new RequestBuilder(rootUrl, getPendingOrders.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OrderResponse>>;
    })
  );
}

getPendingOrders.PATH = '/orders/pending';
