/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItemOrderResponse } from '../../models/item-order-response';

export interface GetCompletedOrders$Params {
  'date-time': string;
}

export function getCompletedOrders(http: HttpClient, rootUrl: string, params: GetCompletedOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ItemOrderResponse>>> {
  const rb = new RequestBuilder(rootUrl, getCompletedOrders.PATH, 'get');
  if (params) {
    rb.query('date-time', params['date-time'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ItemOrderResponse>>;
    })
  );
}

getCompletedOrders.PATH = '/orders/completed';
