/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { DayOfTheWeekAnalysisResponse } from '../models/day-of-the-week-analysis-response';
import { getDayOfTheWeekAverages } from '../fn/orders-admin/get-day-of-the-week-averages';
import { GetDayOfTheWeekAverages$Params } from '../fn/orders-admin/get-day-of-the-week-averages';

@Injectable({ providedIn: 'root' })
export class AdminService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getDayOfTheWeekAverages()` */
  static readonly GetDayOfTheWeekAveragesPath = '/orders/completed/day-of-the-week-average-order-data-for-28days';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDayOfTheWeekAverages()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDayOfTheWeekAverages$Response(params?: GetDayOfTheWeekAverages$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DayOfTheWeekAnalysisResponse>>> {
    return getDayOfTheWeekAverages(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDayOfTheWeekAverages$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDayOfTheWeekAverages(params?: GetDayOfTheWeekAverages$Params, context?: HttpContext): Observable<Array<DayOfTheWeekAnalysisResponse>> {
    return this.getDayOfTheWeekAverages$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DayOfTheWeekAnalysisResponse>>): Array<DayOfTheWeekAnalysisResponse> => r.body)
    );
  }

}
