/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrderedItemsFrequencyResponse } from '../../models/ordered-items-frequency-response';

export interface GetFrequentlyOrderedItemsOfPast30Days$Params {
}

export function getFrequentlyOrderedItemsOfPast30Days(http: HttpClient, rootUrl: string, params?: GetFrequentlyOrderedItemsOfPast30Days$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OrderedItemsFrequencyResponse>>> {
  const rb = new RequestBuilder(rootUrl, getFrequentlyOrderedItemsOfPast30Days.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<OrderedItemsFrequencyResponse>>;
    })
  );
}

getFrequentlyOrderedItemsOfPast30Days.PATH = '/orders/completed/top-ordered-items-of-past-30days';
