/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MonthlyOrderDataResponse } from '../../models/monthly-order-data-response';

export interface GetMonthlyOrderData$Params {
  year: number;
}

export function getMonthlyOrderData(http: HttpClient, rootUrl: string, params: GetMonthlyOrderData$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MonthlyOrderDataResponse>>> {
  const rb = new RequestBuilder(rootUrl, getMonthlyOrderData.PATH, 'get');
  if (params) {
    rb.query('year', params.year, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MonthlyOrderDataResponse>>;
    })
  );
}

getMonthlyOrderData.PATH = '/orders/completed/monthly-order-data';
