/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseItemResponse } from '../../models/page-response-item-response';

export interface GetPageOfItemsByCategory$Params {
  'category-id': string;
  page?: number;
  size?: number;
}

export function getPageOfItemsByCategory(http: HttpClient, rootUrl: string, params: GetPageOfItemsByCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseItemResponse>> {
  const rb = new RequestBuilder(rootUrl, getPageOfItemsByCategory.PATH, 'get');
  if (params) {
    rb.query('category-id', params['category-id'], {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseItemResponse>;
    })
  );
}

getPageOfItemsByCategory.PATH = '/items/category/page';
