/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItemResponse } from '../../models/item-response';

export interface GetItemById$Params {
  'item-id': string;
}

export function getItemById(http: HttpClient, rootUrl: string, params: GetItemById$Params, context?: HttpContext): Observable<StrictHttpResponse<ItemResponse>> {
  const rb = new RequestBuilder(rootUrl, getItemById.PATH, 'get');
  if (params) {
    rb.path('item-id', params['item-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ItemResponse>;
    })
  );
}

getItemById.PATH = '/items/{item-id}';
