/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IdResponse } from '../../models/id-response';
import { LocationRequest } from '../../models/location-request';

export interface SaveOrderLocation$Params {
      body: LocationRequest
}

export function saveOrderLocation(http: HttpClient, rootUrl: string, params: SaveOrderLocation$Params, context?: HttpContext): Observable<StrictHttpResponse<IdResponse>> {
  const rb = new RequestBuilder(rootUrl, saveOrderLocation.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IdResponse>;
    })
  );
}

saveOrderLocation.PATH = '/locations';
