/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { UsersService } from './services/users.service';
import { ServiceRequestsService } from './services/service-requests.service';
import { OrdersService } from './services/orders.service';
import { OrderDetailsService } from './services/order-details.service';
import { LocationsService } from './services/locations.service';
import { ItemsService } from './services/items.service';
import { CategoriesService } from './services/categories.service';
import { AuthenticationService } from './services/authentication.service';
import { OrdersAdminService } from './services/orders-admin.service';
import { AdminService } from './services/admin.service';
import { FilesService } from './services/files.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    UsersService,
    ServiceRequestsService,
    OrdersService,
    OrderDetailsService,
    LocationsService,
    ItemsService,
    CategoriesService,
    AuthenticationService,
    OrdersAdminService,
    AdminService,
    FilesService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
