/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseCategoryResponse } from '../../models/page-response-category-response';

export interface GetPageOfCategories$Params {
  page?: number;
  size?: number;
}

export function getPageOfCategories(http: HttpClient, rootUrl: string, params?: GetPageOfCategories$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseCategoryResponse>> {
  const rb = new RequestBuilder(rootUrl, getPageOfCategories.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseCategoryResponse>;
    })
  );
}

getPageOfCategories.PATH = '/categories/page';
