/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CategoryResponse } from '../../models/category-response';

export interface SearchCategoryByName$Params {
  'category-name': string;
  filter: string;
}

export function searchCategoryByName(http: HttpClient, rootUrl: string, params: SearchCategoryByName$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CategoryResponse>>> {
  const rb = new RequestBuilder(rootUrl, searchCategoryByName.PATH, 'get');
  if (params) {
    rb.path('category-name', params['category-name'], {});
    rb.query('filter', params.filter, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CategoryResponse>>;
    })
  );
}

searchCategoryByName.PATH = '/categories/search/name/{category-name}';
