/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IdResponse } from '../../models/id-response';
import { SelfProfileUpdateRequest } from '../../models/self-profile-update-request';

export interface UpdateSelfProfile$Params {
      body: SelfProfileUpdateRequest
}

export function updateSelfProfile(http: HttpClient, rootUrl: string, params: UpdateSelfProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<IdResponse>> {
  const rb = new RequestBuilder(rootUrl, updateSelfProfile.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IdResponse>;
    })
  );
}

updateSelfProfile.PATH = '/users/update-self-profile';
