/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ItemResponse } from '../../models/item-response';

export interface GetItemsByCategory$Params {
  'category-id': string;
}

export function getItemsByCategory(http: HttpClient, rootUrl: string, params: GetItemsByCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ItemResponse>>> {
  const rb = new RequestBuilder(rootUrl, getItemsByCategory.PATH, 'get');
  if (params) {
    rb.path('category-id', params['category-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ItemResponse>>;
    })
  );
}

getItemsByCategory.PATH = '/items/category/{category-id}';
